version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "generators_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"