spring:
  application:
    name: GeneratorsDiplomaWork
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregate_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true